// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
    static FirebaseOptions get currentPlatform {
        if (kIsWeb) {
          return web;
        }
        switch (defaultTargetPlatform) {
          case TargetPlatform.android:
            return android;
          case TargetPlatform.iOS:
            throw UnsupportedError(
              'DefaultFirebaseOptions have not been configured for ios - '
              'you can reconfigure this by running the FlutterFire CLI again.',
            );
          case TargetPlatform.macOS:
            throw UnsupportedError(
              'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
            );
          case TargetPlatform.windows:
            throw UnsupportedError(
              'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
            );
          case TargetPlatform.linux:
            throw UnsupportedError(
              'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
            );
          default:
            throw UnsupportedError(
              'DefaultFirebaseOptions are not supported for this platform.',
            );
        }
    }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwbERu0qs7avPGH04bdykCTwnOg5lUePM',
    appId: '1:632988435177:web:dc69b13bbc5e734ea4a678',
    messagingSenderId: '632988435177',
    projectId: 'pushnotifications-a6dc0',
    authDomain: 'pushnotifications-a6dc0.firebaseapp.com',
    storageBucket: 'pushnotifications-a6dc0.appspot.com',
    measurementId: 'G-R4NNCE1M6X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8NfB27befBGWJ-tnOxsfGgb8zRHgCYZU',
    appId: '1:632988435177:android:ca53266f2b253712a4a678',
    messagingSenderId: '632988435177',
    projectId: 'pushnotifications-a6dc0',
    storageBucket: 'pushnotifications-a6dc0.appspot.com',
  );

}